server:
  port: 8081
  tomcat:
    threads:
      max: 1
      min-spare: 1

logging:
  level:
    com.test.demo2 : debug

spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            loggerLevel : FULL
